environment:
  ANDROID_HOME: C:\Program Files (x86)\Android\android-sdk
  JAVA_HOME: C:\Program Files\Java\jdk1.7.0\

install:
  - echo y | "%ANDROID_HOME%\tools\android.bat" --silent update sdk --no-ui --all --filter android-23
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t build-tools-23.0.2
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t extra-android-support, extra-android-m2repository

test_script:
  - echo nexusUsername=dummy > library\gradle.properties
  - echo nexusPassword=dummy > library\gradle.properties
  - gradlew.bat clean assemble check
  - gradlew.bat :library:androidJavadocs

build: off